# Generated by Django 4.0.6 on 2022-07-16 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='num_key',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
